setDict = {"canvas_height": 1600,
            "canvas_width": 1600,
            "carMin": 0,
            "carMax": 30,
            "timeMax": 3,
            "timeMin": 1,
            "grid_size": 12,
            "collecting_time": 20000,
            "fps": 100,
            "color": {
                "road": "#808080",
                "background": "bisque",
                "road_mark": "yellow",
                "grid": "#FFFFFF",
                'selected': "red",
                'lane_mark': '#FFFFFF',
                'curve': 'red',
                'debugBtn_on': 'red',
                'debugBtn_off': '#FFFFFF'
            }}